[package]
name = "pact_verifier_cli"
version = "0.9.7"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2021"
description = "Standalone pact verifier for provider pact verification"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_models = "0.2.7"
pact_verifier = { version = "0.13.0", path = "../pact_verifier" }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
clap = "2.33"
regex = "1.5.4"
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
simplelog = "0.10.2"
serde_json = "1.0.78"
anyhow = "1.0.53"
ansi_term = "0.12.1"

[dev-dependencies]
expectest = "0.12.0"
