[package]
name = "pact_verifier_cli"
version = "0.9.15"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2021"
description = "Standalone pact verifier for provider pact verification"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_models = "=0.4.4"
pact_verifier = { version = "0.13.10", path = "../pact_verifier" }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
clap = { version = "3.2.16", features = ["cargo", "env"] }
regex = "1.5.4"
log = "0.4.17"
serde_json = "1.0.79"
anyhow = "1.0.55"
ansi_term = "0.12.1"
maplit = "1.0.2"
tracing = { version = "0.1" }
tracing-core = "0.1.23"
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
tracing-log = "0.1.3"
env_logger = "0.9.0"

[dev-dependencies]
expectest = "0.12.0"
