[package]
name = "pact_mock_server"
version = "0.8.9"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements in process mock server"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.55"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.79"
pact_matching = { version =  "0.12.4", path = "../pact_matching" }
pact_models = "0.3.2"
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
maplit = "1.0.2"
lazy_static = "1.4.0"
uuid = { version = "0.8.2", features = ["v4"] }
itertools = "0.10.3"
tokio = { version = "1", features = ["full"] }
futures = "0.3.21"
hyper = { version = "0.14.17", features = ["full"] }
bytes = "1.1.0"
hyper-rustls = "0.23.0"
rustls = "0.20.4"
tokio-rustls = "0.23.2"
rustls-pemfile = "0.3.0"
thiserror = "1.0.30"
pact-plugin-driver = "0.1.3"

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
env_logger = "0.8"
test-env-log = "0.2.2"
