[package]
name = "pact_ffi"
version = "0.3.6"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>", "Matt Fellows <matt.fellows@onegeek.com.au>", "Andrew Lilley Brinker <abrinker@mitre.org>", "Caleb Stepanian <cstepanian@mitre.org>"]
edition = "2021"
description = "Pact interface for foreign languages."
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver", "ffi"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.57"
pact_matching = { version = "0.12.9", path = "../pact_matching" }
pact_models = "0.4.2"
pact_mock_server = { version = "0.9.1", path = "../pact_mock_server" }
pact_verifier = { version = "0.13.9", path = "../pact_verifier" }
libc = "0.2.125"
zeroize = "1.5.5"
thiserror = "1.0.31"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
bytes = "1.1.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
rand = "0.8.5"
chrono = "0.4.19"
chrono-tz = "=0.6.1" # Pinned this version as 0.6.2 has a dependency that does not compile on Alpine
env_logger = "0.9.0"
itertools = "0.10.3"
onig = { version = "6.3.1", default-features = false }
uuid = { version = "0.8.2", features = ["v4"] }
multipart = { version = "0.18.0", default-features = false, features = ["client", "mock"] }
rand_regex = "0.15.1"
regex-syntax = "0.6.25"
clap = "2.34.0"
regex = "1.5.5"
tokio = { version = "1.18.2", features = ["full"] }
tokio-rustls = "0.23.4"
sxd-document = "0.3.2"
either = "1.6.1"
pact-plugin-driver = "0.1.8"
log = "0.4.17"
tracing = "=0.1.34" # This needs to be the same version across all the libs (i.e. plugin driver)
tracing-core = "=0.1.26"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "tracing-log"] }
tracing-log = "0.1.3"

[dev-dependencies]
expectest = "0.12.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
quickcheck = "1"
test-log = "0.2.10"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[build-dependencies]
os_info = { version = "3.3.0", default-features = false }
