[package]
name = "pact_ffi"
version = "0.1.6"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>", "Matt Fellows <matt.fellows@onegeek.com.au>", "Andrew Lilley Brinker <abrinker@mitre.org>", "Caleb Stepanian <cstepanian@mitre.org>"]
edition = "2021"
description = "Pact interface for foreign languages."
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver", "ffi"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_matching = { version = "0.12.1", path = "../pact_matching" }
pact_models = "0.2.7"
pact_mock_server = { version = "0.8.4", path = "../pact_mock_server" }
pact_verifier = { version = "0.12.2", path = "../pact_verifier" }
anyhow = "1.0.28"
libc = "0.2.69"
zeroize = "1.1.0"
thiserror = "1.0.15"
fern = "0.6.0"
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
serde_json = "1.0.51"
serde = { version = "1.0.128", features = ["derive"] }
bytes = "1.0.1"
lazy_static = "1.4.0"
maplit = "1.0.2"
rand = "0.8"
chrono = "0.4"
chrono-tz = "0.5"
env_logger = "0.8.2"
itertools = "0.10.0"
onig = { version = "6.1.0", default-features = false }
uuid = { version = "0.8", features = ["v4"] }
multipart = { version = "0.17", default-features = false, features = ["client", "mock"] }
rand_regex = "0.15.0"
regex-syntax = "0.6.4"
clap = "2.33.0"
regex = "1.3.9"
simplelog = "0.9"
tokio = { version = "1", features = ["full"] }
sxd-document = "0.3.2"
either = "1.6.1"
pact-plugin-driver = "0.0.16"

[dev-dependencies]
expectest = "0.12.0"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
quickcheck = "1"
test-log = "0.2.8"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[build-dependencies]
os_info = { version = "3.0", default-features = false }
