[package]
name = "pact_ffi"
version = "0.3.0"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>", "Matt Fellows <matt.fellows@onegeek.com.au>", "Andrew Lilley Brinker <abrinker@mitre.org>", "Caleb Stepanian <cstepanian@mitre.org>"]
edition = "2021"
description = "Pact interface for foreign languages."
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver", "ffi"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.55"
pact_matching = { version = "0.12.7", path = "../pact_matching" }
pact_models = "0.4.1"
pact_mock_server = { version = "0.8.11", path = "../pact_mock_server" }
pact_verifier = { version = "0.13.6", path = "../pact_verifier" }
libc = "0.2.119"
zeroize = "1.5.3"
thiserror = "1.0.30"
fern = "0.6.0"
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
bytes = "1.1.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
rand = "0.8.5"
chrono = "0.4.19"
chrono-tz = "0.6.1"
env_logger = "0.9.0"
itertools = "0.10.3"
onig = { version = "6.3.1", default-features = false }
uuid = { version = "0.8.2", features = ["v4"] }
multipart = { version = "0.18.0", default-features = false, features = ["client", "mock"] }
rand_regex = "0.15.1"
regex-syntax = "0.6.25"
clap = "2.34.0"
regex = "1.5.4"
simplelog = "0.9.0"
tokio = { version = "1", features = ["full"] }
sxd-document = "0.3.2"
either = "1.6.1"
pact-plugin-driver = "0.1.6"

[dev-dependencies]
expectest = "0.12.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
quickcheck = "1"
test-log = "0.2.8"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[build-dependencies]
os_info = { version = "3.0", default-features = false }
