[package]
name = "pact_mock_server_cli"
version = "0.7.9"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Standalone pact mock server for consumer pact tests"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.119"
clap = "2.34.0"
serde_json = "1.0.79"
pact_models = "1.0.4"
pact_matching = { version = "1.0.2", path = "../pact_matching" }
pact_mock_server = { version = "0.9.7", path = "../pact_mock_server" }
simplelog = "0.12.0"
log = "0.4.17"
uuid = { version = "1.1.2", features = ["v4"] }
maplit = "1.0.2"
rand = "0.8.5"
webmachine-rust = "0.2.2"
regex = "1.5.4"
lazy_static = "1.4.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
url = "2.2.2"
http = "0.2.6"
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
hyper = "0.14.17"
itertools = "0.10.3"
anyhow = "1.0.55"

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
