[package]
name = "pact_matching"
version = "1.0.6"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements request and response matching logic"
documentation = "https://docs.rs/pact_matching/"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_matching"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_models = "1.0.9"
anyhow = "1.0.57"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
hex = "0.4.3"
onig = { version = "6.4.0", default-features = false }
maplit = "1.0.2"
lazy_static = "1.4.0"
semver = "1.0.9"
lenient_semver = "0.4.2"
itertools = "0.10.3"
rand = "0.8.5"
sxd-document = "0.3.2"
ansi_term = "0.12.1"
difference = "2.0.0"
base64 = "0.21.0"
uuid = { version = "1.1.2", features = ["v4"] }
nom = "7.1.1"
chrono = { version = "0.4.19", features = ["std", "clock"], default_features = false }
tree_magic_mini = "3.0.3"
multipart = { version = "0.18.0", default-features = false, features = ["server"] }
http = "0.2.7"
mime = "0.3.16"
bytes = { version = "1.1.0", features = ["serde"] }
tokio = { version = "1.23.0", features = ["full"] }
pact-plugin-driver = "0.3.3"
md5 = "0.7.0"
tracing = "0.1.37" # This needs to be the same version across all the libs (i.e. plugin driver, pact ffi)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. plugin driver, pact ffi)

#     Updating async-trait v0.1.64 -> v0.1.66
#    Updating axum v0.6.9 -> v0.6.11
#    Updating axum-core v0.3.2 -> v0.3.3
#    Updating chrono v0.4.23 -> v0.4.24
#    Updating cxx v1.0.91 -> v1.0.92
#    Updating cxx-build v1.0.91 -> v1.0.92
#    Updating cxxbridge-flags v1.0.91 -> v1.0.92
#    Updating cxxbridge-macro v1.0.91 -> v1.0.92
#    Updating darling v0.14.3 -> v0.14.4
#    Updating darling_core v0.14.3 -> v0.14.4
#    Updating darling_macro v0.14.3 -> v0.14.4
#    Updating futures v0.3.26 -> v0.3.27
#    Updating futures-channel v0.3.26 -> v0.3.27
#    Updating futures-core v0.3.26 -> v0.3.27
#    Updating futures-executor v0.3.26 -> v0.3.27
#    Updating futures-io v0.3.26 -> v0.3.27
#    Updating futures-macro v0.3.26 -> v0.3.27
#    Updating futures-sink v0.3.26 -> v0.3.27
#    Updating futures-task v0.3.26 -> v0.3.27
#    Updating futures-util v0.3.26 -> v0.3.27
#    Removing http-range-header v0.3.0
#    Updating hyper v0.14.24 -> v0.14.25
#    Updating io-lifetimes v1.0.5 -> v1.0.6
#    Updating itoa v1.0.5 -> v1.0.6
#    Updating libc v0.2.139 -> v0.2.140
#    Updating pact-plugin-driver v0.3.2 -> v0.3.3
#    Updating pact_models v1.0.4 -> v1.0.6
#    Updating prettyplease v0.1.23 -> v0.1.24
#    Updating proc-macro2 v1.0.51 -> v1.0.52
#    Updating quote v1.0.23 -> v1.0.26
#    Updating rayon v1.6.1 -> v1.7.0
#    Updating rayon-core v1.10.2 -> v1.11.0
#    Updating rustix v0.36.8 -> v0.36.9
#    Updating rustversion v1.0.11 -> v1.0.12
#    Updating ryu v1.0.12 -> v1.0.13
#    Updating scratch v1.0.3 -> v1.0.5
#    Updating semver v1.0.16 -> v1.0.17
#    Updating serde v1.0.152 -> v1.0.155
#    Updating serde_derive v1.0.152 -> v1.0.155
#    Updating serde_json v1.0.93 -> v1.0.94
#    Updating serde_with v2.2.0 -> v2.3.1
#    Updating serde_with_macros v2.2.0 -> v2.3.1
#    Updating simplelog v0.12.0 -> v0.12.1
#    Updating socket2 v0.4.7 -> v0.4.9
#    Updating thiserror v1.0.38 -> v1.0.39
#    Updating thiserror-impl v1.0.38 -> v1.0.39
#    Updating toml_edit v0.19.4 -> v0.19.6
#    Removing tower-http v0.4.0
#    Updating unicode-bidi v0.3.10 -> v0.3.11
#    Updating unicode-ident v1.0.6 -> v1.0.8
#    Updating utf8parse v0.2.0 -> v0.2.1
#    Updating windows-targets v0.42.1 -> v0.42.2
#    Updating windows_aarch64_gnullvm v0.42.1 -> v0.42.2
#    Updating windows_aarch64_msvc v0.42.1 -> v0.42.2
#    Updating windows_i686_gnu v0.42.1 -> v0.42.2
#    Updating windows_i686_msvc v0.42.1 -> v0.42.2
#    Updating windows_x86_64_gnu v0.42.1 -> v0.42.2
#    Updating windows_x86_64_gnullvm v0.42.1 -> v0.42.2
#    Updating windows_x86_64_msvc v0.42.1 -> v0.42.2
#    Updating winnow v0.3.3 -> v0.3.5

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["rustls-tls-native-roots", "json"]

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
env_logger = "0.10.0"
hamcrest2 = "0.3.0"
test-log = { version = "0.2.11", features = ["trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log", "fmt"] }
ntest = "0.9.0"
pretty_assertions = "1.2.1"
rstest = "0.16.0"
