[package]
name = "pact_verifier"
version = "0.13.6"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements provider verification functions"
documentation = "https://docs.rs/pact_verifier/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.57"
libc = "0.2.125"
serde = "1.0.137"
serde_json = "1.0.81"
pact_matching = { version = "0.12.7", path = "../pact_matching" }
pact_models = "0.4.1"
pact-plugin-driver = "0.1.6"
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
maplit = "1.0.2"
lazy_static = "1.4.0"
itertools = "0.10.3"
ansi_term = "0.12.1"
regex = "1.5.5"
difference = "2.0.0"
futures = "0.3.21"
mime = "0.3.16"
bytes = "1.1.0"
tokio = { version = "1.18.2", features = ["full"] }
http = "0.2.7"
async-trait = "0.1.53"
thiserror = "1.0.31"
base64 = "0.13.0"
urlencoding = "2.1.0"
tracing = { version = "0.1", features = [ "log-always" ] }

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["rustls-tls-native-roots", "blocking", "json"]

[dependencies.serde_with]
version = "1.13.0"
features = ["json"]

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
env_logger = "0.8"
pact_consumer = { version = "0.9.1", path = "../pact_consumer" }
