[package]
name = "pact_consumer"
version = "0.9.2"
authors = ["Ronald Holshausen <uglyog@gmail.com>", "Eric Kidd <git@randomhacks.net>"]
edition = "2021"
description = "Pact-Rust module that provides support for writing consumer pact tests"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_consumer"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT AND Apache-2.0"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.119"
pact_models = "0.3.3"
pact_matching = { version = "0.12.5", path = "../pact_matching" }
pact_mock_server = { version = "0.8.9", path = "../pact_mock_server" }
log = "=0.4.14" # This needs to be the same version across all the libs (i.e. plugin driver)
maplit = "1.0.2"
lazy_static = "1.4.0"
regex = "1.5.4"
serde_json = "1.0.79"
itertools = "0.10.3"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
futures = "0.3.21"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.55"
pact-plugin-driver = "0.1.3"
bytes = "1.1.0"
async-trait = "0.1.52"
tracing = "0.1.32"

[dev-dependencies]
quickcheck = "1"
env_logger = "0.8"
expectest = "0.12.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
serde = { version = "^1.0", features = ["derive"] }
rand = "0.8.4"
tokio-test = "0.4.2"
