name: Pact-Rust Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, beta ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Tests
        uses: marcopolo/cargo@master # TODO: - use actions-rs/cargo@v1 when PR merged https://github.com/actions-rs/cargo/pull/59
        with:
          working-directory: rust
          command: test
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Build Components
        uses: marcopolo/cargo@master
        with:
          working-directory: rust
          command: build
      - name: Run the C FFI tests
        if: runner.os == 'Linux'
        with:
          working-directory: c/consumer-verification
        run: |
          alocal
          autoconf
          automake --add-missing
          ./configure
          make
          src/consumer-verification basic ../../rust/target/debug/libpact_mock_server_ffi.so
          src/consumer-verification error ../../rust/target/debug/libpact_mock_server_ffi.so
      - name: Clippy
        uses: marcopolo/cargo@master
        with:
          working-directory: rust
          command: clippy
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install doxygen
        if: runner.os == 'Linux'
        run: sudo apt-get install -y doxygen
      - name: Build pact_matching_ffi with CMake
        run: ./ci-build.sh
        working-directory: rust/pact_matching_ffi
        shell: bash
        if: runner.os == 'Linux'
